#******** Towny politics ********
set_cost: 0
change_cost: 0
#0 - speed
#0 - tax, 1 - chunk cost, 2 - income
forms:
  1:
    name: "Демократия"
    player_boost: []
    town_boost:
      - "0:0.85"
  2:
    name: "Монархия"
    player_boost: []
    town_boost:
      - "1:0.8"
  3:
    name: "Либерализм"
    player_boost: []
    town_boost:
      - "2:50"
  4:
    name: "Социализм"
    player_boost:
      - "0:1"
    town_boost: []

#******** Towny builds ********
buildings:
  1:
    name: "Золотая шахта"
    levels:
      1:
        items_cost:
          - "COBBLESTONE:64"
          - "IRON_PICKAXE:1"
        boost:
          - "1:64"
        items_income: []
      2:
        items_cost:
          - "COBBLESTONE:128"
          - "IRON_PICKAXE:2"
          - "OAK_PLANKS:64"
        boost:
          - "1:128"
        items_income: []
      3:
        items_cost:
          - "COBBLESTONE:256"
          - "IRON_PICKAXE:5"
          - "OAK_PLANKS:256"
        boost:
          - "1:192"
        items_income: [ ]
      4:
        items_cost:
          - "COBBLESTONE:256"
          - "IRON_PICKAXE:15"
          - "OAK_PLANKS:256"
          - "SPRUCE_PLANKS:256"
        boost:
          - "1:256"
        items_income: [ ]
  2:
    name: "Плантация"
    levels:
      1:
        items_cost:
          - "GLASS:64"
          - "IRON_HOE:1"
        boost:
          - "0:0"
        items_income:
          - "BAMBOO:16"
      2:
        items_cost:
          - "GLASS:128"
          - "IRON_HOE:2"
          - "WATER_BUCKET:1"
        boost:
          - "0:0"
        items_income:
          - "SWEET_BERRIES:16"

  3:
    name: "Завод"
    levels:
      1:
        items_cost:
          - "COBBLESTONE:128"
          - "FURNACE:16"
          - "ANVIL:1"
          - "COAL:128"
        boost:
          - "0:0"
        items_income:
          - "IRON_INGOT:64"
      2:
        items_cost:
          - "COBBLESTONE:256"
          - "FURNACE:32"
          - "ANVIL:3"
          - "COAL:256"
        boost:
          - "0:0"
        items_income:
          - "IRON_INGOT:128"
      3:
        items_cost:
          - "COBBLESTONE:256"
          - "FURNACE:64"
          - "ANVIL:5"
          - "COAL:256"
          - "IRON_PICKAXE:5"
        boost:
          - "0:0"
        items_income:
          - "IRON_INGOT:192"


  4:
    name: "Библиотека"
    levels:
      1:
        items_cost:
          - "BOOKSHELF:15"
          - "ENCHANTING_TABLE:1"
        boost:
          - "2:15"
        items_income: []
      2:
        items_cost:
          - "BOOKSHELF:30"
          - "ENCHANTING_TABLE:2"
          - "LAPIS_LAZULI:128"
        boost:
          - "2:30"
        items_income: [ ]


